'use strict';
const $=id=>document.getElementById(id);
const REGIONS=['梧桐街道','凤鸣街道','高桥街道','濮院镇','乌镇镇','屠甸镇','石门镇','河山镇','洲泉镇','大麻镇','崇福镇'];
let records=[],map,markers,db,worker,busy=false,activeId,lastGeocode=0;
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
const option=(v,t=v)=>`<option value="${escapeHTML(v)}">${escapeHTML(t)}</option>`;
$('region-filter').innerHTML=option('','全部乡镇 / 街道')+REGIONS.map(x=>option(x)).join('')+option('待核实');
$('edit-region').innerHTML=option('','待核实')+REGIONS.map(x=>option(x)).join('')+option('桐乡市外');
function located(r){return Number.isFinite(r.lat)&&Number.isFinite(r.lon)&&Math.abs(r.lat)<=90&&Math.abs(r.lon)<=180}
function pending(r){return !located(r)||!r.time||!r.region||!r.confirmed}
function filtered(){return records.filter(r=>(!$('region-filter').value||($('region-filter').value==='待核实'?!r.region:r.region===$('region-filter').value))&&(!$('status-filter').value||($('status-filter').value==='located'?located(r):pending(r))))}
let amapMarkers=[],geocoder,amapReady;
function config(){return window.QIANSHOU_MAP_CONFIG||{}}
function gcj(r){const [lat,lon]=wgs(r);if(lon>72.004&&lon<137.8347&&lat>.8293&&lat<55.8271){const [a,b]=gcjOffset(lat,lon);return[lon+b,lat+a]}return[lon,lat]}
function initMap(){if(!$('online-location').checked)return;const c=config();if(!c.key||(!c.code&&!c.proxy)){if($('map-status'))$('map-status').textContent='地图服务暂未启用，可在检查记录中手动打开高德位置。';return;}if(c.proxy)window._AMapSecurityConfig={serviceHost:c.proxy};else window._AMapSecurityConfig={securityJsCode:c.code||''};
amapReady=(window.AMap?Promise.resolve():new Promise((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>reject(Error('高德加载超时')),20000);script.src='https://webapi.amap.com/maps?v=2.0&key='+encodeURIComponent(c.key)+'&plugin=AMap.Geocoder,AMap.ToolBar,AMap.Scale';script.onload=()=>{clearTimeout(timer);if(!window.AMap){reject(Error('高德鉴权失败'));return}resolve()};script.onerror=()=>{clearTimeout(timer);reject(Error('高德加载失败'))};document.head.appendChild(script)})).then(()=>{$('map').innerHTML='';map=new AMap.Map('map',{center:[120.565,30.63],zoom:11,viewMode:'2D',mapStyle:'amap://styles/normal',resizeEnable:true});map.addControl(new AMap.ToolBar({position:'RT'}));map.addControl(new AMap.Scale());geocoder=new AMap.Geocoder({city:'330483',radius:500,extensions:'all'});map.on('error',()=>{$('map-error').hidden=false});render();fit();$('map-error').hidden=true;}).catch(e=>{$('map-error').hidden=false;toast('高德地图连接失败，请检查地图配置。')});}
function drawHighde(){if(!map||!window.AMap)return;map.remove(amapMarkers);amapMarkers=[];filtered().filter(located).forEach((r,i)=>{const marker=new AMap.Marker({position:gcj(r),content:'<div class="pin"><span>'+(i+1)+'</span></div>',offset:new AMap.Pixel(-16,-36),title:r.place||r.name});marker.on('click',()=>openDetail(r.id));amapMarkers.push(marker)});map.add(amapMarkers);}
// GCJ02 / BD09 input coordinates are converted to WGS84 for standard GPS export.
function gcjOffset(lat,lon){const x=lon-105,y=lat-35,pi=Math.PI;let a=-100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x));let b=300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x));a+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;b+=(20*Math.sin(6*x*pi)+20*Math.sin(2*x*pi))*2/3;a+=(20*Math.sin(y*pi)+40*Math.sin(y*pi/3))*2/3;b+=(20*Math.sin(x*pi)+40*Math.sin(x*pi/3))*2/3;a+=(160*Math.sin(y*pi/12)+320*Math.sin(y*pi/30))*2/3;b+=(150*Math.sin(x*pi/12)+300*Math.sin(x*pi/30))*2/3;const rad=lat*pi/180,s=Math.sin(rad),m=1-.006693421622965943*s*s;return[a*180/(6335552.717000426/(m*Math.sqrt(m))*pi),b*180/(6378245/Math.sqrt(m)*Math.cos(rad)*pi)]}
function wgs(r){let lat=r.lat,lon=r.lon;if(r.system==='BD09'){const x=lon-.0065,y=lat-.006,z=Math.sqrt(x*x+y*y)-.00002*Math.sin(y*Math.PI*3000/180),t=Math.atan2(y,x)-.000003*Math.cos(x*Math.PI*3000/180);lon=z*Math.cos(t);lat=z*Math.sin(t)}if(r.system!=='WGS84'&&lon>72.004&&lon<137.8347&&lat>.8293&&lat<55.8271){let guessLat=lat,guessLon=lon;for(let i=0;i<5;i++){const [a,b]=gcjOffset(guessLat,guessLon);guessLat-=guessLat+a-lat;guessLon-=guessLon+b-lon}return[guessLat,guessLon]}return[lat,lon]}
function render(){$('fit').disabled=!map;const list=filtered();$('total').innerHTML=records.length+'<small>张</small>';$('located').innerHTML=records.filter(located).length+'<small>张</small>';$('regions').innerHTML=new Set(records.map(r=>r.region).filter(r=>REGIONS.includes(r))).size+'<small>个</small>';$('pending').innerHTML=records.filter(pending).length+'<small>张</small>';$('result-count').textContent=`共 ${list.length} 条检查记录`;$('empty').hidden=!!list.length;$('export').disabled=!list.length;$('clear').disabled=!records.length;$('rows').innerHTML=list.map(r=>`<tr><td><img src="${r.url}" alt="检查照片缩略图"><span class="filename" title="${escapeHTML(r.name)}">${escapeHTML(r.name)}</span></td><td>${escapeHTML(r.place||'待补充位置')}</td><td>${escapeHTML(r.time?r.time.replace('T',' '):'待补充时间')}</td><td>${escapeHTML(r.region||'待核实')}</td><td class="coords">${located(r)?`${r.lat.toFixed(6)}, ${r.lon.toFixed(6)}<br>${r.system}`:'未识别经纬度'}</td><td><span class="badge ${pending(r)?'pending':''}">${r.confirmed&&!pending(r)?'已核实':located(r)?'已定位 · 待核实':'待补充'}</span></td><td><button data-edit="${r.id}">查看 / 核实</button> <button data-delete="${r.id}">移除</button></td></tr>`).join('');$('photo-list').innerHTML=records.slice(-6).reverse().map(r=>`<div class="photo-item" tabindex="0" role="button" data-edit="${r.id}" aria-label="查看 ${escapeHTML(r.name)}"><img src="${r.url}" alt=""><div><strong>${escapeHTML(r.place||r.name)}</strong><small>${escapeHTML(r.region||'区域待核实')} · ${located(r)?'已定位':'未定位'}</small></div></div>`).join('');drawHighde()}
function fit(){if(!map)return;if(amapMarkers.length)map.setFitView(amapMarkers,false,[45,45,45,45],15);else map.setZoomAndCenter(11,[120.565,30.63])}
function requestResult(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function initDB(){try{const req=indexedDB.open('qianshou-quality-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('photos',{keyPath:'id'});db=await requestResult(req);const rows=await requestResult(db.transaction('photos').objectStore('photos').getAll());records=rows.map(r=>({...r,url:URL.createObjectURL(r.blob)}))}catch{toast('本机存储不可用，请在离开前导出汇总表。')}}
async function save(r){if(!db||!$('remember-photos').checked)return;const {url,...data}=r;try{await new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(data);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)})}catch{toast('保存失败，可能是浏览器空间不足；请导出汇总表。')}}
async function remove(id){const r=records.find(r=>r.id===id);if(db)await requestResult(db.transaction('photos','readwrite').objectStore('photos').delete(id));if(r)URL.revokeObjectURL(r.url);records=records.filter(r=>r.id!==id);render()}
function parseOCR(text){const clean=text.replace(/[，]/g,',').replace(/[。]/g,'.').replace(/(?<=\d)[oO](?=\d)/g,'0');const found=[...clean.matchAll(/(-?\d{1,3}[.]\d{4,9})\s*[°º]?\s*([NSEW])?/gi)];let lat,lon;for(const m of found){let n=Number(m[1]),dir=m[2]?.toUpperCase();if(dir==='S'||dir==='W')n=-Math.abs(n);if((dir==='N'||dir==='S'||Math.abs(n)>=20&&Math.abs(n)<=40)&&lat===undefined)lat=n;else if((dir==='E'||dir==='W'||Math.abs(n)>=100&&Math.abs(n)<=130)&&lon===undefined)lon=n}const date=clean.match(/(20\d{2})[.\-/年\s]+(\d{1,2})[.\-/月\s]+(\d{1,2})[日\s]+(\d{1,2})[:：](\d{2})/);let time='';if(date){const [_,y,m,d,h,min]=date;const v=`${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}T${h.padStart(2,'0')}:${min}`;const check=new Date(v);if(!isNaN(check)&&check.getMonth()+1===Number(m)&&check.getDate()===Number(d)&&+h<24&&+min<60)time=v}const place=(clean.replace(/(?<=[\u4e00-\u9fff])\s+(?=[\u4e00-\u9fff])/g,'').match(/([\u4e00-\u9fff]{2,10}(?:村|社区))/)||[])[1]||'';return{lat,lon,time,watermarkPlace:place}}
async function getWorker(){if(!window.Tesseract)throw Error('识别组件未加载');if(!worker){worker=await Tesseract.createWorker('eng+chi_sim',1,{logger:m=>{if(m.status==='recognizing text')$('progress-label').textContent='正在识别照片经纬度与时间…'}});await worker.setParameters({tessedit_pageseg_mode:'6'})}return worker}
async function ocr(blob){const image=await createImageBitmap(blob),canvas=document.createElement('canvas');const h=Math.round(image.height*.28),scale=Math.min(2,2600/image.width);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(h*scale);const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,image.height-h,image.width,h,0,0,canvas.width,canvas.height);image.close();const w=await getWorker();let text=(await w.recognize(canvas)).data.text,parsed=parseOCR(text);if(!Number.isFinite(parsed.lat)||!Number.isFinite(parsed.lon)||!parsed.time){const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const a=pixels.data[i],b=pixels.data[i+1],c=pixels.data[i+2],white=a>180&&b>180&&c>180&&Math.max(a,b,c)-Math.min(a,b,c)<55;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=white?0:255}ctx.putImageData(pixels,0,0);text+='\n'+(await w.recognize(canvas)).data.text;parsed=parseOCR(text)}return{...parsed,rawOCR:text}}
async function geocode(r){if(!located(r)||!$('online-location').checked)return;if(amapReady)await amapReady;if(!geocoder){r.addressSource='地图服务暂未启用，所属乡镇可手动确认';return}try{const wait=Math.max(0,300-(Date.now()-lastGeocode));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));lastGeocode=Date.now();const data=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('地址查询超时')),15000);geocoder.getAddress(gcj(r),(status,result)=>{clearTimeout(timer);if(status==='complete'&&result.info==='OK')resolve(result.regeocode);else reject(Error(result.info||'查询失败'))})});const address=data.addressComponent||{},town=String(address.township||'');r.region=REGIONS.find(t=>town.includes(t))||REGIONS.find(t=>String(data.formattedAddress).includes(t))||'';if(String(address.adcode)!=='330483'&&address.adcode)r.region='桐乡市外';r.place=r.watermarkPlace||data.formattedAddress||r.place;r.fullAddress=data.formattedAddress;r.addressSource='高德地图逆地理编码';}catch{await fallbackAddress(r)}}

let lastFallback=0;
async function fallbackAddress(r){try{const wait=Math.max(0,1100-(Date.now()-lastFallback));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));lastFallback=Date.now();const [lat,lon]=wgs(r),res=await fetch('https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat='+lat+'&lon='+lon+'&zoom=18&addressdetails=1&accept-language=zh-CN',{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('Unavailable');const d=await res.json();if(d.error)throw Error('Unavailable');const a=d.address||{},area=Object.values(a).join(' ');r.region=REGIONS.find(t=>area.includes(t))||'';if(!r.region&&!/桐乡|Tongxiang/i.test(area))r.region='桐乡市外';r.fullAddress=d.display_name;r.place=r.watermarkPlace||[a.road,a.neighbourhood,a.hamlet,a.village].filter(Boolean).join(' · ')||d.display_name||r.place;r.addressSource='备用地址查询 · OpenStreetMap';}catch{r.addressSource='地址暂不可用；所属乡镇请手动确认'}}

function progress(n,total,label){$('progress').value=Math.round(n/total*100);$('progress-pct').textContent=`${n} / ${total}`;$('progress-label').textContent=label}
function setBusy(value){busy=value;for(const id of ['upload-top','drop','clear','do-clear','remember-photos','online-location'])$(id).disabled=value;}
async function upload(files){if(busy)return;const valid=[...files].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type)||/\.(jpe?g|png|webp)$/i.test(f.name));if(!valid.length){toast('请选择 JPG、PNG 或 WebP 照片。');return}if(valid.length>100){toast('每批最多 100 张，请分批上传。');return}setBusy(true);let duplicates=0;try{for(let i=0;i<valid.length;i++){const file=valid[i];progress(i,valid.length,`读取第 ${i+1} 张照片…`);if(file.size>30*1024*1024){toast(`${file.name} 超过 30 MB，已跳过。`);continue}const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(records.some(r=>r.hash===hash)){duplicates++;continue}const r={id:crypto.randomUUID(),name:file.name,hash,blob:file,url:URL.createObjectURL(file),system:$('coord-system').value,source:'水印文字识别',region:'',place:'',time:'',confirmed:false};try{if(!window.exifr)throw Error('GPS 组件未加载');const exif=await exifr.parse(file,{gps:true});if(Number.isFinite(exif?.latitude)&&Number.isFinite(exif?.longitude)){r.lat=exif.latitude;r.lon=exif.longitude;r.system='WGS84';r.source='照片内嵌 GPS';}const date=exif?.DateTimeOriginal||exif?.CreateDate;if(date instanceof Date&&!isNaN(date)){r.time=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}}catch{}try{if(!located(r)||!r.time){const result=await ocr(file);if(!located(r)){r.lat=result.lat;r.lon=result.lon}if(!r.time)r.time=result.time;r.rawOCR=result.rawOCR;r.watermarkPlace=result.watermarkPlace;r.place=result.watermarkPlace||r.place}}catch(e){r.error='水印识别不可用，请手动填写经纬度与时间'}if(located(r)){progress(i,valid.length,'查询具体位置与所属区域…');await geocode(r)}records.push(r);await save(r);render();progress(i+1,valid.length,`已处理 ${i+1} 张照片`)}fit();toast(`本批处理完成${duplicates?`，跳过 ${duplicates} 张重复照片`:''}。请对照原图核实识别结果。`)}catch(e){toast('处理中断，已完成的记录已保留；请重试剩余照片。');console.error(e)}finally{setBusy(false);$('files').value='';render()}}
function openDetail(id){const r=records.find(r=>r.id===id);if(!r)return;activeId=id;if(located(r)){const pos=gcj(r);$('open-amap').href='https://uri.amap.com/marker?position='+pos.join(',')+'&name='+encodeURIComponent('检查位置')+'&coordinate=gaode&callnative=0';$('open-amap').hidden=false;$('map-link-note').hidden=false}else{$('open-amap').removeAttribute('href');$('open-amap').hidden=true;$('map-link-note').hidden=true}$('detail-image').src=r.url;$('detail-source').textContent=`${r.source} · ${r.addressSource||'所属区域待核实'}${r.error?' · '+r.error:''}`;$('edit-place').value=r.place||'';$('edit-time').value=r.time||'';$('edit-lat').value=located(r)?r.lat:'';$('edit-lon').value=located(r)?r.lon:'';$('edit-region').value=r.region||'';$('edit-system').value=r.system;$('edit-confirmed').checked=!!r.confirmed;$('detail').showModal()}
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openDetail(edit.dataset.edit);if(del){remove(del.dataset.delete).catch(()=>toast('移除失败，请重试。'))}});
document.addEventListener('keydown',e=>{const el=e.target.closest('.photo-item');if(el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openDetail(el.dataset.edit)}});
$('edit-form').addEventListener('submit',async e=>{e.preventDefault();const r=records.find(r=>r.id===activeId);if(!r)return;const lat=$('edit-lat').value,lon=$('edit-lon').value;if(!!lat!==!!lon){toast('请同时填写经度和纬度。');return}r.lat=lat?Number(lat):undefined;r.lon=lon?Number(lon):undefined;r.place=$('edit-place').value.trim();r.time=$('edit-time').value;r.region=$('edit-region').value;r.system=$('edit-system').value;r.confirmed=$('edit-confirmed').checked;if(r.confirmed&&(!located(r)||!r.region||!r.time)){toast('核实前请补齐经纬度、拍摄时间与所属区域。');return}await save(r);$('detail').close();render();fit();toast('检查信息已保存。')});
$('close-dialog').onclick=()=>$('detail').close();$('upload-top').onclick=$('drop').onclick=()=>{if(!busy)$('files').click()};$('files').onchange=e=>upload(e.target.files);$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');upload(e.dataTransfer.files)};
$('fit').onclick=fit;for(const id of ['region-filter','status-filter'])$(id).onchange=()=>{render();fit()};
function csvCell(s){let value=String(s??'');if(/^[=+@\-\t\r]/.test(value))value="'"+value;return '"'+value.replace(/"/g,'""')+'"'}
$('export').onclick=()=>{const list=filtered();if(!list.length)return;const head=['照片文件名','具体位置','拍摄时间','所属乡镇/街道','纬度（原始）','经度（原始）','原始坐标系','标准纬度（WGS84）','标准经度（WGS84）','识别来源','核实状态'];const lines=[head,...list.map(r=>{const pos=located(r)?wgs(r):['',''];return[r.name,r.place,r.time?.replace('T',' '),r.region||'待核实',r.lat,r.lon,r.system,...pos.map(n=>typeof n==='number'?n.toFixed(6):n),r.source,r.confirmed&&!pending(r)?'已核实':'待核实']})];const blob=new Blob(['\ufeff'+lines.map(line=>line.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`牵手物业品质考核汇总_${new Date().toLocaleDateString('sv-SE')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已导出 ${list.length} 条记录，可用 Excel 打开。`)};
$('clear').onclick=()=>$('confirm-clear').showModal();$('cancel-clear').onclick=()=>$('confirm-clear').close();$('do-clear').onclick=async()=>{try{if(db)await requestResult(db.transaction('photos','readwrite').objectStore('photos').clear());records.forEach(r=>URL.revokeObjectURL(r.url));records=[];$('confirm-clear').close();render();fit();toast('当前工作空间已清空。')}catch{toast('清空失败，请重试。')}};
try{$('remember-photos').checked=localStorage.getItem('qianshou-remember-photos')==='true'}catch{}
$('remember-photos').onchange=async()=>{try{localStorage.setItem('qianshou-remember-photos',String($('remember-photos').checked))}catch{}if($('remember-photos').checked){for(const r of records)await save(r);toast('当前记录已保存到本机。')}else toast('新上传照片不再长期保存。已保存记录可通过“清空记录”删除。')};
$('online-location').onchange=async()=>{if(!$('online-location').checked){if(map){map.destroy();map=undefined;amapMarkers=[];geocoder=undefined;$('map').innerHTML='<div class="map-setup"><span>⌖</span><h2>在线地图已关闭</h2><p>照片识别与汇总仍可使用。</p></div>'}return}initMap();if(amapReady)await amapReady;if(!geocoder){toast('地图服务暂未启用，可手动在高德打开位置。');$('online-location').checked=false;return}setBusy(true);try{for(let i=0;i<records.length;i++){progress(i,records.length,'查询乡镇地址…');await geocode(records[i]);await save(records[i])}render();fit()}finally{setBusy(false)}};
(async()=>{initMap();await initDB();render();fit()})();
